- CHANGELOG.md
- package-lock.json
- package.json
- src/index.js
- Add more server side logs
- Adds start script used after deployment
> Add more server side logs

- src/integrations/braytech.js
i recommend a light test first!
> new api baby

- CHANGELOG.md
- package-lock.json
- package.json
> :lock: Updates dependencies

- .eslintrc.js
- CHANGELOG.md
- package-lock.json
- package.json
- :arrow_up: Updated dependencies
> :arrow_up: Updated dependencies

- .circleci/config.yml
- CHANGELOG.md
- index.js
- package-lock.json
- package.json
- :sparkle: Added thanks for 3,000 followers on tomorrows scheduled tweet
- :wrench: Fixed CI/CD to not build for production during non master branch runs
> :sparkle: Adds thanks for 3,000 followers on tomorrows scheduled tweet

- CHANGELOG.md
- index.js
- package-lock.json
- package.json
- :sparkle: Removed thanks for 3,000 followers on tomorrows scheduled tweet
> :sparkle: Removed thanks for 3,000 followers on tomorrows scheduled tweet

- .gitignore
- CHANGELOG.md
- index.js
- package-lock.json
- package.json
- src/integrations/dynamodb.js
- src/util/get-mod-details.js
- src/util/get-mod-tweet-message.js
- src/util/get-time-wording.js
- test/integration/braytech.js
- test/unit/get-mod-details.js
- test/unit/get-mod-tweet-message.js
- test/unit/get-ordinal.js
- :bug: Fixes bug with historic context for each tweet
> Fix historic details

- CHANGELOG.md
- index.js
- package-lock.json
- package.json
- :bug: Fixed bug with daily tweet call
> Fix tweet call

- CHANGELOG.md
- index.js
- package-lock.json
- package.json
- src/util/get-mod-details.js
- test/unit/get-mod-details.js
- :bug: Fixed bug with last sold dates by avoiding adding the mod to the
database until after the tweet was successful
> Fix last sold bug

- CHANGELOG.md
- package-lock.json
- package.json
- terraform/modules/lambda/main.tf
- :wrench: Updated Lambda timeout from 30 seconds to 60 seconds
> :wrench: Updated Lambda timeout from 30 seconds to 60 seconds

- CHANGELOG.md
- package-lock.json
- package.json
- terraform/modules/dynamodb/main.tf
- :wrench: Updated DynamoDB Terraform to not destroy the database on `terraform destroy`
- :wrench: Reduced DynamoDB read and write capacity
> Update dynamo database IaaC

- CHANGELOG.md
- package-lock.json
- package.json
- src/integrations/braytech.js
- :wrench: Updated Braytech endpoint from upstream change
- :arrow_up: Updated dependencies
> :wrench: Updated Braytech endpoint from upstream change

- CHANGELOG.md
- package-lock.json
- package.json
- terraform/modules/dynamodb/main.tf
:wrench: Added point in time recovery for DynamoDB database
> :wrench: Added point in time recovery for DynamoDB database

- .circleci/config.yml
- .npmrc
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- commitlint.config.js
- package-lock.json
- package.json
- release.config.js
> Add semantic release

- package-lock.json
- package.json
feat: cleans up build after adding semantic-release
> feat: cleans up build after adding semantic-release

- package-lock.json
- package.json
- release.config.js
> fix(semantic-release): fixes package automation

- .circleci/config.yml
> fix(cicd): fixes release order

- .circleci/config.yml
Moves deployment to only tags following semantic versioning
> fix(cicd): fixes release after tag

- .circleci/config.yml
- README.md
- release.config.js
Switches default branch to main
> feat: switches default branch to main

- .github/dependabot.yml
Adds dependabot config overriding commit message type
> fix: commit message config

- package-lock.json
- terraform/modules/event-bridge/main.tf
Resets tweet to reset (was reset +1 min)
> feat: resets tweet to reset (was reset +1 min)

- terraform/modules/event-bridge/main.tf
corrects aws eventbridge cron syntax
> fix: corrects aws eventbridge cron syntax

- index.js
- package-lock.json
- package.json
- src/integrations/twitter.js
> feat: updates tweet trigger logic

- index.js
- package-lock.json
- src/integrations/banshee-44-mods.js
> feat: adds more error handling

- src/integrations/banshee-44-mods.js
- adds limited banshee44mods retries
> feat: adds limited banshee44mods retries

- terraform/modules/iam/main.tf
Renames AWS IAM names to kebab case
> feat: renames iam names

- README.md
> docs: fixes readme logo

- .circleci/config.yml
- package-lock.json
- src/util/get-mod-info.js
fix: no sales in last year bug
> fix: no sales in last year bug

- .circleci/config.yml
- package-lock.json
- package.json
@semantic-release/release-notes-generator    ~9.0.2  →    ~9.0.3     
aws-sdk                                    ~2.922.0  →  ~2.943.0     
eslint                                      ~7.28.0  →   ~7.30.0     
husky                                        ~4.3.8  →    ~7.0.1     
nconf                                       ~0.11.2  →   ~0.11.3     
semantic-release                            ~17.4.3  →   ~17.4.4     
tap-spec                                     ~2.2.2  →    ~5.0.0
> Update dependencies 2020 07 11

- .github/workflows/release.yml
- .github/workflows/test.yml
> fix: twitter integration test

- .github/workflows/auto-merge.yml
Adds auto merge to dependabot PR's where the dependency is either `minor` or `patch` changes.
> feat: adds dependabot auto merge

- .github/CODEOWNERS
- .github/dependabot.yml
- CHANGELOG.md
- release.config.js
chore: updates dependabot config
> chore: updates dependabot config

- release.config.js
chore: adds support for chore in release notes
> chore: adds support for chore in release notes

- .github/dependabot.yml
- CHANGELOG.md
- package-lock.json
- package.json
- release.config.js
> fix: semantic-release setup

- terraform/main.tf
- terraform/modules/dynamodb/main.tf
- terraform/modules/iam/main.tf
- terraform/modules/iam/variables.tf
> feat: adds items table

- terraform/modules/dynamodb/main.tf
fix: renames vendor field to source
> fix: renames vendor field to source

- .eslintrc.js
- src/integrations/destiny-insights-backend.js
- src/integrations/dynamodb.js
- src/tweet-types/ada-1.js
- src/tweet-types/banshee-44.js
- src/tweet-types/xur.js
- src/util/is-new-inventory.js
- test/integration/ada-1.js
- test/integration/banshee-44.js
- test/integration/xur.js
feat: adopts backend changes (closes #264)
> feat: adopts backend changes

- src/integrations/dynamodb.js
- src/tweet-types/ada-1.js
- src/tweet-types/banshee-44.js
- src/tweet-types/xur.js
fix: adds back different timeframes to last sold lookups (closes #269)
> fix: adds back different timeframes to last sold lookups

- terraform/modules/dynamodb/main.tf
feat: removes legacy databases
> feat: removes legacy databases

- terraform/main.tf
- terraform/modules/dynamodb/main.tf
- terraform/modules/iam/main.tf
- terraform/modules/iam/variables.tf
> feat: removes legacy tables

- src/tweet-types/high-stat-legendary-armor.js
feat: updates high stat armor message
> feat: updates high stat armor message

- src/tweet-types/mods.js
fix: updates mod selling phrasing
> fix: updates mod selling phrasing

- src/util/get-mod-last-sold-info.js
feat: revises last sold message
> feat: revises last sold message

- index.js
- package.json
- src/tweet-types/high-stat-legendary-armor.js
- src/tweet-types/wish-list-legendary-weapons.js
- src/util/is-armor-high-stat.js
- test/unit/is-armor-high-stat.js
feat: adds wishlist tweets aligning to DIM wishlists
> feat: adds wishlist tweets aligning to DIM wishlists

- terraform/modules/event_bridge/main.tf
feat: reduces tweet check timespan from reset + 7 hours to reset + 3 hours to reduce costs and wasted compute and database reads
> feat: reduces tweet check timespan

- terraform/modules/dynamodb/main.tf
feat: reduces database provisions
> feat: reduces database provisions

- .github/dependabot.yml
feat: adds terraform to dependabot
> feat: adds terraform to dependabot

- terraform/modules/event_bridge/main.tf
feat: updates eventbridge to run every fiveteen mins
> feat: updates eventbridge to run every fiveteen mins

- index.js
- src/integrations/dynamodb.js
- src/tweet-types/mods.js
- refactor: removes vanguard high stat armor tweets due to revised possible stat totals
- refactor: revised method to find mod types
- refactor: splits mod tweets by vendor due to character contraints
- refactor: removes Xur tweets until his first arrival
> feat: adds support for witch queen

- index.js
- src/tweet-types/high-stat-legendary-armor.js
- src/tweet-types/wish-list-weapons.js
- src/tweet-types/xur-exotics.js
feat: adds support for Xur selling Hawkmoon and Dead Mans Tale
> feat: adds support for Xur selling Hawkmoon and Dead Mans Tale

- index.js
feat: moves Xur exotic tweet higher
> feat: moves Xur exotic tweet higher

- terraform/modules/lambda/main.tf
> feat: increases timeout

- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/update-dependencies.yml
> fix: updates cicd
